name: Update SOTA Map

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: write

env:
  CALLSIGN: ${{ vars.CALLSIGN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Cache openstreetmap tiles
        uses: actions/cache@v4
        with:
          key: osm-tile-cache
          path: tile_cache/

      - name: Generate sota.html
        run: |
          ./generate_map.py
          mkdir output
          mv sota.html output/

      - name: Install png postprocess tooling
        run: |
          sudo apt-get install -y --no-install-recommends pngcrush pngquant

      - name: Generate sota.png
        run: |
          ./generate_map_png.py
          mkdir -p output
          ./postprocess-png.sh sota.png output/sota.png

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
